name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
#  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
        working-directory: digital-debris
      - name: Build
        run: pnpm run build
        working-directory: digital-debris
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: digital-debris/dist
